export const profissoesList = [
  'Administrador',
  'Advogado',
  'Agricultor',
  'Analista de Sistemas',
  'Aposentado',
  'Arquiteto',
  'Artista',
  'Assistente Social',
  'Autônomo',
  'Bancário',
  'Biomédico',
  'Bombeiro',
  'Comerciante',
  'Contador',
  'Cozinheiro',
  'Dentista',
  'Designer',
  'Do lar',
  'Economista',
  'Educador Físico',
  'Eletricista',
  'Enfermeiro',
  'Engenheiro',
  'Empresário',
  'Estudante',
  'Farmacêutico',
  'Fisioterapeuta',
  'Funcionário Público',
  'Garçom',
  'Jornalista',
  'Mecânico',
  'Médico',
  'Motorista',
  'Nutricionista',
  'Pedreiro',
  'Policial',
  'Professor',
  'Psicólogo',
  'Recepcionista',
  'Secretário',
  'Segurança',
  'Soldado',
  'Técnico',
  'Vendedor',
  'Veterinário'
].sort()
